CREAM/urls.py
from django.conf.urls import include, url

from django.contrib.auth.decorators import login_required

from .views import HomeView, DashboardView

# Enable the admin site:
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    # Base URL displays home page
    # url(r'^$', login_required()(HomeView.as_view()),name="home"),
    url(r'^$', DashboardView.as_view()),
    
    # URL for the admin site:
    url(r'^admin/', include(admin.site.urls)),
    
    # URL for the comments framework
    url(r'^comments/', include('django_comments.urls')),
    
    # URLs for applications
    url(r'^services/',include('services.urls')),
    url(r'^projects/',include('projects.urls')),
    url(r'^reports/',include('reports.urls')),
    url(r'^users/',include('users.urls')),
    url(r'^qualifications/',include('qualifications.urls')),
    url(r'^recruitment/',include('recruitment.urls')),
]

qualifications/urls.py
from django.conf.urls import url

from qualifications.views import SkillCategoriesListView, SkillCategoryDetailView, SkillCategoryCreateView, SkillCategoryUpdateView, SkillCategoryDeleteView
from qualifications.views import SkillsListView, SkillDetailView, SkillCreateView, SkillUpdateView, SkillDeleteView, AddSkillFromSkillCategoryView
from qualifications.views import JobsListView, JobDetailView, JobCreateView, JobUpdateView, JobDeleteView, AddPositionFromEmployeeView
from qualifications.views import PositionsListView, OpenPositionsListView, PositionDetailView, PositionCreateView, PositionUpdateView, PositionDeleteView, AddEmployeePositionFromPositionView
from qualifications.views import EmployeeSkillsListView, EmployeeSkillDetailView, EmployeeSkillCreateView, EmployeeSkillUpdateView, EmployeeSkillDeleteView
from qualifications.views import JobProfileSkillsListView, JobProfileSkillDetailView, JobProfileSkillCreateView, JobProfileSkillUpdateView, JobProfileSkillDeleteView
from qualifications.views import EmployeePositionsListView, EmployeePositionDetailView, EmployeePositionCreateView, EmployeePositionUpdateView, EmployeePositionDeleteView

from recruitment.views import AddApplicantFromPositionView


urlpatterns = [
    
    ##################################
    # Skill Categories 
    url(r'^skill_categories/$', SkillCategoriesListView.as_view(), name='skillcategories_list'),
    url(r'^skill_categories/(?P<pk>\d+)/$', SkillCategoryDetailView.as_view(), name='skillcategory_detail'),
    url(r'^skill_categories/create/$', SkillCategoryCreateView.as_view(), name='create_skillcategory' ),
    url(r'^skill_categories/(?P<pk>\d+)/update/$', SkillCategoryUpdateView.as_view(), name='update_skillcategory' ),
    url(r'^skill_categories/(?P<pk>\d+)/delete/$', SkillCategoryDeleteView.as_view(), name='delete_skillcategory' ),
    
    url(r'^skill_categories/(?P<pk>\d+)/add_skill/$', AddSkillFromSkillCategoryView.as_view(), name='add_skill' ),
    ##################################
    
    ##################################
    # Skills 
    url(r'^skills/$', SkillsListView.as_view(), name='skills_list'),
    url(r'^skills/(?P<pk>\d+)/$', SkillDetailView.as_view(), name='skill_detail' ),
    url(r'^skills/create/$', SkillCreateView.as_view(), name='create_skill'),
    url(r'^skills/(?P<pk>\d+)/update/$', SkillUpdateView.as_view(), name='update_skill' ),
    url(r'^skills/(?P<pk>\d+)/delete/$', SkillDeleteView.as_view(), name='delete_skill' ),
    ##################################
        
    ##################################
    # Jobs
    url(r'^jobs/$', JobsListView.as_view(), name='jobs_list'),
    url(r'^jobs/(?P<pk>\d+)/$', JobDetailView.as_view(), name='job_detail' ),
    url(r'^jobs/create/$', JobCreateView.as_view(), name='create_job' ),
    url(r'^jobs/(?P<pk>\d+)/update/$', JobUpdateView.as_view(), name='update_job' ),
    url(r'^jobs/(?P<pk>\d+)/delete/$', JobDeleteView.as_view(), name='delete_job' ),
    
    url(r'^jobs/(?P<pk>\d+)/add_position/$', AddPositionFromEmployeeView.as_view(), name='add_position' ),
    ##################################
    
    ##################################
    # Positions
    url(r'^positions/all$', PositionsListView.as_view(), name='all_positions_list'),
    url(r'^positions/$', OpenPositionsListView.as_view(), name='positions_list'),
    url(r'^positions/(?P<pk>\d+)/$', PositionDetailView.as_view(), name='position_detail' ),
    url(r'^positions/create/$', PositionCreateView.as_view(), name='create_position' ),
    url(r'^positions/(?P<pk>\d+)/update/$', PositionUpdateView.as_view(), name='update_position' ),
    url(r'^positions/(?P<pk>\d+)/delete/$', PositionDeleteView.as_view(), name='delete_position' ),
    
    url(r'^positions/(?P<pk>\d+)/add_employee/$', AddEmployeePositionFromPositionView.as_view(), name='add_employeeposition' ),
    url(r'^positions/(?P<pk>\d+)/add_applicant/$', AddApplicantFromPositionView.as_view(), name='add_applicantfromposition' ),
    ##################################
        
    ##################################
    # Employee Skills 
    url(r'^employee_skills/$', EmployeeSkillsListView.as_view(), name='employeeskills_list'),
    url(r'^employee_skills/(?P<pk>\d+)/$', EmployeeSkillDetailView.as_view(), name='employeeskills_detail' ),
    url(r'^employee_skills/create/$', EmployeeSkillCreateView.as_view(), name='create_employeeskills' ),
    url(r'^employee_skills/(?P<pk>\d+)/update/$', EmployeeSkillUpdateView.as_view(), name='update_employeeskills' ),
    url(r'^employee_skills/(?P<pk>\d+)/delete/$', EmployeeSkillDeleteView.as_view(), name='delete_employeeskills' ),
    ##################################
    
    ##################################
    # job profile Skills 
    url(r'^job_profile_skills/$', JobProfileSkillsListView.as_view(), name='jobprofileskills_list'),
    url(r'^job_profile_skills/(?P<pk>\d+)/$', JobProfileSkillDetailView.as_view(), name='jobprofileskill_detail'),
    url(r'^job_profile_skills/create/$', JobProfileSkillCreateView.as_view(), name='create_jobprofileskill'),
    url(r'^job_profile_skills/(?P<pk>\d+)/update/$', JobProfileSkillUpdateView.as_view(), name='update_jobprofileskill'),
    url(r'^job_profile_skills/(?P<pk>\d+)/delete/$', JobProfileSkillDeleteView.as_view(), name='delete_jobprofileskill'),
    ##################################
    
    ##################################
    # Employee Positions 
    url(r'^employee_positions/$', EmployeePositionsListView.as_view(), name='employeepositions_list'),
    url(r'^employee_positions/(?P<pk>\d+)/$', EmployeePositionDetailView.as_view(), name='employeeposition_detail' ),
    url(r'^employee_positions/create/$', EmployeePositionCreateView.as_view(), name='create_employeeposition' ),
    url(r'^employee_positions/(?P<pk>\d+)/update/$', EmployeePositionUpdateView.as_view(), name='update_employeeposition' ),
    url(r'^employee_positions/(?P<pk>\d+)/delete/$', EmployeePositionDeleteView.as_view(), name='delete_employeeposition' ),
    ##################################
    
]

qualifications/models.py
from datetime import date

from django.db import models

from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils import timezone
from core.models import Location
from projects.models import Project

# The Qualifications app depends on the users app,
# we need to link against the Employee object
from users.models import Employee


class SkillCategory (models.Model):
    '''The SkillCategory object allows to categorize Skills (surprise !)'''
    
    name = models.CharField(max_length=64)
    description = models.TextField()
    
    class Meta:
        '''Default order is on name'''
        ordering = ['name']
   
    def __str__(self):
        '''Returns the name when printing object'''
        return str(self.name)
        
    def get_skills(self):
        '''Returns the list of skills belonging to this category. This method
        is just for convenience'''
        return self.skill_set.all()





class Skill (models.Model):
    '''The Skill Object describes somthing (usually a Process, Method ot Tool)
    for which an employee has some knowledge. It is linked to 
    - Employees through the EmployeeSkill object
    - Jobs through the JobSkill object'''
    
    name = models.CharField(max_length=64)
    enabled = models.BooleanField(default=True)
    description = models.TextField()
    category = models.ForeignKey(SkillCategory)
    
    class Meta:
        '''Default order is category, then name'''
        ordering = ['category', 'name']
    
    def __str__(self):
        '''Returns the category and name when printing this object'''
        return str(self.category.name) + ": " + str(self.name)
        
    def get_employees(self):
        '''Returns the list of employees with this skill. This method
        is just for convenience'''
        return self.employeeskill_set.all()

    def get_jobs(self):
        '''Returns the list of jobs requiring this skill. This method
        is just for convenience'''
        return self.jobprofileskill_set.all()




class Job (models.Model):
    '''A job is a daily activity requiring some Skills. It is linked to Skills 
    through the JobSkill object'''
    
    name = models.CharField(max_length=64)
    description = models.TextField()
    
    class Meta:
        # Default order is on name
        ordering = ['name']
    
    def __str__(self):
        '''Returns the name when printing object'''
        return str(self.name)
     
    def get_profile_skills(self):
        '''Returns the list of skills required for this job. This method
        is just for convenience'''
        return self.jobprofileskill_set.all()
        
    def get_employees(self):
        return self.jobemployee_set.all()
        


class PositionStatus(models.Model):
    id = models.CharField(primary_key=True, max_length=1)
    name = models.CharField(max_length=64)
    css_class = models.CharField(max_length=64)
    
    def __str__(self):
        return str(self.name)



class Profile (models.Model):
    '''A profile is attached to a job to define the qualification levels for this job'''
    
    name = models.CharField(max_length=64)
    description = models.TextField()
    
    class Meta:
        ordering = ['name']
    
    def __str__(self):
        return str(self.name)

 

class Position(models.Model):
    '''A Position is the implementation of a Job in a specific context'''
    
    title = models.CharField(max_length=128,null=True,blank=True)
    job = models.ForeignKey(Job)
    profile = models.ForeignKey(Profile)
    project = models.ForeignKey(Project)
    status = models.ForeignKey(PositionStatus)
    location = models.ForeignKey(Location)
    publish_date = models.DateField(default=timezone.now)
    headcount = models.DecimalField(max_digits=5,decimal_places=2)
    comment = models.TextField(null=True, blank=True)
    start_date = models.DateField(null=True, blank=True)

    class Meta:
        ordering=['project','job','profile']

    def __str__(self):
        if self.title is not None:
            return str(self.title)
        else:
            return str(self.project) + " - " + str(self.job) + " - " + str(self.location)
            
   

class EmployeeSkill(models.Model):
    '''Defines the Skills levels for an employee. The level should be between 
    1 (basic knowledge) and 4 (intergalactic guru).'''    
    
    employee = models.ForeignKey(Employee)
    skill = models.ForeignKey(Skill)
    level = models.IntegerField(validators=[MinValueValidator(1),MaxValueValidator(4)])
    
    class Meta:
        #Make sure that there is unicity for an employee and a skill
        unique_together = ("employee", "skill")
        # Default order is employee, then level (desc), then skill
        ordering = ['employee','-level','skill']
    
    def __str__(self):
        '''Returns the employee, skill and level when printing object'''
        return str(self.employee) + " : " + self.skill.name + " : " + str(self.level)
        
    

class JobProfileSkill(models.Model):
    ''''Defines the Skills levels required for a Job. The level should be between 
    1 (basic knowledge) and 5 (intergalactic guru).'''
    
    job = models.ForeignKey(Job)
    profile = models.ForeignKey(Profile)
    skill = models.ForeignKey(Skill)
    level = models.IntegerField(validators=[MinValueValidator(1),MaxValueValidator(5)])
    
    class Meta:
        #Make sure that there is unicity for a job and a skill
        unique_together = ("job", "profile", "skill")
        # Default order is job, then profile, then level (desc), then skill
        ordering = ['job', 'profile', '-level','skill']
        
    def __str__(self):
        '''Returns the job, skill and level when printing object'''
        return str(self.job.name) + " : " + str(self.profile.name) +" : " + str(self.skill.name) + " : " + str(self.level)

        

class EmployeePositionStatus(models.Model):
    id = models.CharField(primary_key=True, max_length=1)
    name = models.CharField(max_length=64)
    css_class = models.CharField(max_length=64)
    
    def __str__(self):
        return str(self.name)
    
        
class EmployeePosition(models.Model):
    '''Defines the Positions that are linked to an amployee'''
    
    employee = models.ForeignKey(Employee)
    position = models.ForeignKey(Position)
    status = models.ForeignKey(EmployeePositionStatus)
    start_date = models.DateField(null=True,blank=True)
    end_date = models.DateField(null=True,blank=True)
    comments = models.TextField()
    
    
    def __str__(self):
        return str(self.employee) + ": " + str(self.position)

qualifications/templates/employeeposition_detail.html
<!-- We need to display this page in a full layout -->
{% extends "base.html" %}

{% block content %}

<!-- Include the object property -->
{% include "employeeposition_property.html" %}

<!-- Include the object property -->
{% include "common/object_actions.html" %}

<br/>

{% include "common/comments.html" with object=employeeposition next_url="employeeposition_detail" %}


{% endblock %}

qualifications/templates/employeeposition_form.html
{% extends "base.html" %}

{% block content %}

{% include "fa-decoration.html" with title="Update Employee Position" icon="fa-bullhorn" block="main" %}

{% include "common/standard_form.html" %}

{% endblock %}

qualifications/templates/employeeskill_detail.html
<!-- We need to display this page in a full layout -->
{% extends "base.html" %}

{% block content %}

<!-- Include the object property -->
{% include "employeeskill_property.html" %}

<!-- Include the object property -->
{% include "common/object_actions.html" %}

<hr/>

{% endblock %}

qualifications/templates/employeeskill_form.html
{% extends "base.html" %}

{% block content %}

{% include "decoration.html" with title="Update Employee Skill" icon="employee_skill.png" block="main" %}

{% include "common/standard_form.html" %}

{% endblock %}

qualifications/templates/job_property.html
{% include "fa-decoration.html" with title="Job properties" icon="fa-briefcase" block="main" %}
<table class="table table-hover">
    <tr><th>name</th><td>{{job.name}}</td></tr>
    <tr><th>description</th><td>{{ job.description|linebreaks }}</td></tr>
</table>

qualifications/templates/jobprofileskill_detail.html
<!-- We need to display this page in a full layout -->
{% extends "base.html" %}

{% block content %}

<!-- Include the object property -->
{% include "jobprofileskill_property.html" %}

<!-- Include the object property -->
{% include "common/object_actions.html" %}

{% endblock %}

qualifications/templates/jobprofileskill_property.html
{% include "fa-decoration.html" with title="Job Skill properties" icon="fa-dashboard" block="main" %}
<table class="table table-hover">
    <tr><th>job</th><td><a href="{% url "job_detail" jobprofileskill.job.id %}">{{ jobprofileskill.job }}</a></td></tr>
    <tr><th>skill</th><td><a href="{% url "skill_detail" jobprofileskill.skill.id %}">{{ jobprofileskill.skill}}</td></tr>
    <tr><th>profile</th><td>{{ jobprofileskill.profile}}</td></tr>
    <tr><th>level</th><td>{{ jobprofileskill.level }}</td></tr>
</table>

qualifications/templates/jobprofileskill_table.html
{% include "fa-decoration.html" with title=title|default:"Jobs, Profiles & Skills list" icon=icon|default:"fa-dashboard" %}

{% if jobprofileskills_list %}
<table class="table table-condensed table-bordered table-hover dataTable">
    <thead>
        <tr>
            <th>job</th>
            <th>skill</th>
            <th>profile</th>
            <th>level</th>
        </tr>
    </thead>
    <tbody>
{% for jobprofileskill in jobprofileskills_list %}
    <tr>
        <td><a href="{% url "job_detail" jobprofileskill.job.id %}">{{ jobprofileskill.job.name }}</a></td>
        <td><a href="{% url "skill_detail" jobprofileskill.skill.id %}">{{ jobprofileskill.skill }}</a></td>
        <td>{{ jobprofileskill.profile }}</td>
        <td><a href="{% url "jobprofileskill_detail" jobprofileskill.id %}">{{ jobprofileskill.level }}</a></td>
    </tr>
{% endfor %}
    </tbody>
</table>
{% else %}
<p>No job, profile and skills found.</p>
{% endif %}

qualifications/templates/position_detail.html
<!-- We need to display this page in a full layout -->
{% extends "base.html" %}

{% block content %}

<!-- Include the object property -->
{% include "position_property.html" %}

<!-- Include the object property -->
{% include "common/object_actions.html" %}

<br/>

{% include "common/comments.html" with object=position next_url="position_detail" %}

<hr/>

{% include "employeeposition_table.html" with employeepositions_list=position.employeeposition_set.all icon="fa-user" %}
<a href="{% url "add_employeeposition" position.id %}"><i class="fa fa-plus"></i>Add Employee</a>

<hr/>

{% comment %}
In the following line, instead of using applicantposition_set.all, we use applicant_position.all because
of the related_name attribute for Position in ApplicantPosition model
{% endcomment %}
{% include "applicantposition_table.html" with applicantpositions_list=position.applicant_position.all icon="fa-child" %}
<a href="{% url "add_applicantfromposition" position.id %}"><i class="fa fa-plus"></i>Add Applicant</a>

{% endblock %}

qualifications/templates/position_property.html
{% include "fa-decoration.html" with title="Position properties" icon="fa-bullhorn" block="main" %}
<table class="table table-hover">
    <tr><th>title</th><td>{{ position }}</td></tr>
    <tr><th>job</th><td><a href="{% url "job_detail" position.job.id %}">{{position.job}}</a></td></tr>
    <tr><th>profile</th><td>{{ position.profile }}</td></tr>
    <tr><th>project</th><td><a href="{% url "project_detail" position.project.id %}">{{ position.project}}</a></td></tr>
    <tr><th>status</th><td><div class="label {{ position.status.css_class }}">{{ position.status }}</div></td></tr>
    <tr><th>location</th><td>{{ position.location }}</td></tr>
    <tr><th>start date</th><td>{{ position.start_date }} </td></tr>
    <tr><th>publish date</th><td>{{ position.publish_date }}</td></tr>
    <tr><th>headcount</th><td>{{ position.headcount }}</td></tr>
    <tr><th>comment</th><td>{{ position.comment|linebreaksbr }}</td></tr>
</table>

qualifications/templates/skill_confirm_delete.html
{% extends "base.html" %}
{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Skill Categories" "skillcategories_list" %}
    {% breadcrumb skill.category "skillcategory_detail" skill.category.id %}
    {% breadcrumb skill.name "skill_detail" skill.id %}
    {% breadcrumb "Delete skill" "" %}
{% endblock %}

{% block content %}

{% render_breadcrumbs %}

<div class="bg-warning" align="center">Do you really want to delete this Skill ?</div>

{% include "skill_property.html" %}
  
<form method="POST">
    {% csrf_token %}
    {{ form }}
    {% include "common/form_buttons.html" %}
</form>
{% endblock %}

qualifications/templates/skill_form.html
{% extends "base.html" %}

{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Skill Categories" "skillcategories_list" %}
    {% if skill.id %}
        {% breadcrumb skill.category "skillcategory_detail" skill.category.id %}
        {% breadcrumb skill.name "skill_detail" skill.id %}
    {% endif %}
    {% breadcrumb "Edit Skill" "" %}
{% endblock %}

{% block content %}

{% render_breadcrumbs %}

{% include "fa-decoration.html" with title="Update Skill" icon="fa-graduation-cap" block="main" %}

{% include "common/standard_form.html" %}

{% endblock %}

qualifications/templates/skill_property.html
{% include "fa-decoration.html" with title="Skill properties" icon="fa-graduation-cap" block="main" %}
<table class="table table-hover">
    <tr><th>category</th><td><a href="{% url "skillcategory_detail" skill.category.id %}">{{skill.category}}</a></td></tr>
    <tr><th>name</th><td>{{skill.name}}</td></tr>
    <tr><th>enabled</th><td>{{skill.enabled}}</td></tr>
    <tr><th>description</th><td>{{ skill.description}}</td></tr>
</table>

qualifications/templates/skillcategory_detail.html
<!-- We need to display this page in a full layout -->
{% extends "base.html" %}

{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Skill Categories" "skillcategories_list" %}
    {% breadcrumb skillcategory "skillcategory_detail" skillcategory.id %}
{% endblock %}

{% block content %}

{% render_breadcrumbs %}

<!-- Include the object property -->
{% include "skillcategory_property.html" %}

<!-- Include the object property -->
{% include "common/object_actions.html" %}

<hr/>

{% include "skill_table.html" with skills_list=skillcategory.get_skills %}
<a href="{% url "add_skill" skillcategory.id %}"><i class="fa fa-plus"></i>Add skill</a>


{% endblock %}