CREAM/urls.py
from django.conf.urls import include, url

from django.contrib.auth.decorators import login_required

from .views import HomeView, DashboardView

# Enable the admin site:
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    # Base URL displays home page
    # url(r'^$', login_required()(HomeView.as_view()),name="home"),
    url(r'^$', DashboardView.as_view()),
    
    # URL for the admin site:
    url(r'^admin/', include(admin.site.urls)),
    
    # URL for the comments framework
    url(r'^comments/', include('django_comments.urls')),
    
    # URLs for applications
    url(r'^services/',include('services.urls')),
    url(r'^projects/',include('projects.urls')),
    url(r'^reports/',include('reports.urls')),
    url(r'^users/',include('users.urls')),
    url(r'^qualifications/',include('qualifications.urls')),
    url(r'^recruitment/',include('recruitment.urls')),
]

projects/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import permission_required, login_required

from django.views.generic import DetailView, ListView, UpdateView, CreateView, DeleteView
from projects.models import Project, Deliverable, DeliverableVolume

from projects.views import ProjectListView, FilteredProjectListView, ProjectDetailView, ProjectUpdateView, ProjectCreateView, ProjectDeleteView
from projects.views import DeliverableListView, DeliverableDetailView, DeliverableUpdateView, DeliverableCreateView, DeliverableDeleteView, AddDeliverableFromProjectView
from projects.views import AddDeliverableVolumeView, DeliverableVolumeUpdateView
from qualifications.views import AddPositionFromProjectView

urlpatterns = [
    ##################################
    # Projects 
    url(r'^projects/$', ProjectListView.as_view(), name='projects_list'),
    url(r'^projects/(?P<pk>\d+)/$', ProjectDetailView.as_view(), name='project_detail'),
    url(r'^projects/create/$', ProjectCreateView.as_view(), name='create_project'),
    url(r'^projects/(?P<pk>\d+)/update/$', ProjectUpdateView.as_view(), name='update_project'),
    url(r'^projects/(?P<pk>\d+)/delete/$', ProjectDeleteView.as_view(), name='delete_project'),
    
    # Add deliverable to a project
    url(r'^projects/(?P<pk>\d+)/add_deliverable/$', AddDeliverableFromProjectView.as_view(), name='add_deliverable'),
    # Add position to a project
    url(r'^projects/(?P<pk>\d+)/add_position/$', AddPositionFromProjectView.as_view(), name='add_projectposition'),
    url(r'^projects/(?P<filter>.+)/$', FilteredProjectListView.as_view(),name='projects_list_status'),
    ##################################
    
    
    ##################################
    # Deliverables
    url(r'^deliverables/$', DeliverableListView.as_view(), name='deliverables_list' ),
    url(r'^deliverables/(?P<pk>\d+)/$', DeliverableDetailView.as_view(), name='deliverable_detail'),
    url(r'^deliverables/create/$', DeliverableCreateView.as_view(), name='create_deliverable'),
    url(r'^deliverables/(?P<pk>\d+)/update/$', DeliverableUpdateView.as_view(), name='update_deliverable'),
    url(r'^deliverables/(?P<pk>\d+)/delete/$', DeliverableDeleteView.as_view(), name='delete_deliverable'),
    
    # Add volume to a deiverable
    url(r'^deliverables/(?P<pk>\d+)/add_volume/$', AddDeliverableVolumeView.as_view(), name='add_deliverablevolume'),
    ##################################
    
    
    ##################################
    # Deliverable Volumes
    url(r'^deliverablevolumes/(?P<pk>\d+)/$', login_required()(DetailView.as_view( model=DeliverableVolume, template_name='deliverablevolume_detail.html', )), name='deliverablevolume_detail'),
    url(r'^deliverablevolumes/(?P<pk>\d+)/update/$', DeliverableVolumeUpdateView.as_view(), name='update_deliverablevolume'),
    #url(r'^deliverablevolumes/(?P<pk>\d+)/delete/$', permission_required('projects.delete_deliverablevolume')(DeleteDeliverableVolumeView.as_view()), name='delete_deliverablevolume'),
    ##################################

]

projects/models.py
# -*- coding: utf-8 -*-
from datetime import date

from django.db import models
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse

import reversion

from users.models import Employee
from services.models import Service

class ProjectStatus(models.Model):
    
    id = models.CharField(primary_key=True, max_length=1)
    name = models.CharField(max_length=64)
    css_class = models.CharField(max_length=64)
    
    def __str__(self):
        return str(self.name)


class Project (models.Model):
    '''A class to handle projects'''
    
    NATCO_CHOICES = (
        ('D','CIMPA GmbH'),
        ('F','CIMPA SAS'),
        ('U','CIMPA Ltd'),
        )
    
    name = models.CharField(max_length=64, verbose_name="project name")
    number = models.CharField(max_length=32, unique=True, verbose_name="project number")
    description = models.TextField()
    date_start = models.DateField(null=True, blank=True, verbose_name="project start date", help_text='YYYY-MM-DD' )
    date_end = models.DateField(null=True, blank=True, verbose_name="project end date", help_text='YYYY-MM-DD' )
    customer_name = models.CharField(max_length=128, null=True, blank=True)
    customer_siglum = models.CharField(max_length=16, null=True, blank=True)
    wiki_link = models.URLField(null=True, blank=True)
    project_leader = models.ForeignKey(Employee, null=True, blank=True, related_name="project_leader")
    department = models.CharField(max_length=2,null=True, blank=True, verbose_name="CIMPA department")
    natco = models.CharField(max_length=2, choices=NATCO_CHOICES, verbose_name="turnover allocation natco", null=True, blank=True)
    status = models.ForeignKey(ProjectStatus)
    
    class Meta:
        ordering = ["number", "name"]
        
    
    def __str__(self):
        return self.number + ": " + str(self.name)
        
    def get_authorizations(self):
        return self.authorization_set.all()
        
    def get_deliverables(self):
        return self.deliverable_set.all()
        
    def get_tasks(self):
        tasks = list()
        for deliverable in self.get_deliverables():
            tasks += deliverable.task_set.all()
            
        return tasks
    
    def get_total_turnover(self):
        turnover = 0
        for deliverable in self.deliverable_set.all():
            turnover += deliverable.get_turnover()
        return turnover
        
    def get_turnover_per_year(self):
        year_min = self.date_start.year
        year_max = self.date_end.year
        turnover = dict()
        for year in range(year_min,year_max+1):
            year_turnover = 0
            for deliverable in self.deliverable_set.all():
                year_turnover += deliverable.get_turnover_year(year)
            turnover[year] = year_turnover
        return turnover
    
    def get_positions(self):
        return self.position_set.all()

# Register this object in reversion, so that we can track its history
#reversion.register(Project)




def validate_positive(value):
    if value < 0:
        raise ValidationError(u'%s is not a positive value !' % value)


class Deliverable (models.Model):
    
    SERVICE_OWNER_APPROVAL_CHOICES = (
        ('P','Pending'),
        ('A','Approved'),
        ('R','Rejected')
        )
    
    project = models.ForeignKey(Project, on_delete=models.PROTECT, verbose_name="project name")
    service = models.ForeignKey(Service, on_delete=models.PROTECT, verbose_name="service family / service")
    code = models.CharField(max_length=32, null=True, blank=True, verbose_name="project deliverable identifier")
    name = models.CharField(max_length=128, verbose_name="project deliverable name")
    description = models.TextField()
    acceptance_criteria = models.TextField(null=True, blank=True)
    unit_time = models.IntegerField(verbose_name="unit time (mn)", null=True, blank=True, editable=False, validators=[validate_positive]) # Unit time is not used for the moment
    turnover = models.DecimalField(max_digits=12, decimal_places=2, verbose_name="turnover (€)", null=True, blank=True, editable=False, validators=[validate_positive]) # FIXME: Turnover will be computed, to be removed from datamodel
    
    class Meta:
        ordering = ['project','code','name']
    
    def __str__(self):
        return str(self.name)
        
    def get_tasks(self):
        return self.task_set.all()
        
    def get_turnover(self):
        turnover = 0
        for volume in self.deliverablevolume_set.all():
            if volume.quantity != None and volume.unit_price != None:
                turnover += volume.quantity * volume.unit_price
        return turnover
        

    def get_turnover_year(self,year):
        
        date_start = date(year,1,1).toordinal()
        date_end = date(year,12,31).toordinal()
        year_range = range(date_start,date_end+1)
        days_year = len(year_range)
        
        year_turnover = 0
        
        for volume in self.get_volumes():
            date_volume_start = volume.date_start.toordinal()
            date_volume_end = volume.date_end.toordinal()
            volume_range = range(date_volume_start,date_volume_end+1)
            days_volume = len(volume_range)
            
            intersect = list(set(volume_range) & set(year_range))
            days_intersect = len(intersect)
            
            volume_price = round((volume.get_total_price()/days_volume)*days_intersect,2)
            
            year_turnover += volume_price
            
        return year_turnover


    def get_volumes(self):
        return self.deliverablevolume_set.all()
        
    def get_total_volume(self):
        volumes = self.get_volumes()
        total = 0
        for volume in volumes:
            total += volume.quantity
        return total
        
# Register this object in reversion, so that we can track its history
#reversion.register(Deliverable)



class DeliverableVolume(models.Model):

    deliverable = models.ForeignKey(Deliverable)
    date_start = models.DateField(help_text='YYYY-MM-DD')
    date_end = models.DateField(help_text='YYYY-MM-DD')
    quantity = models.IntegerField(null=True, blank=True)
    unit_price = models.DecimalField(max_digits=10, decimal_places=2, default=0, null=True, blank=True)

    class Meta:
        ordering = ['deliverable','date_start']
        
    def __str__(self):
        return str(self.deliverable.name) + ' : ' + str(self.date_start) + " : " + str(self.date_end) + " : " + str(self.quantity)
        
    def get_total_price(self):
        return self.quantity * self.unit_price

# Register this object in reversion, so that we can track its history
#reversion.register(DeliverableVolume)

projects/views.py
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView
from django.core.urlresolvers import reverse_lazy

from core.views import LoginRequiredMixin, PermissionRequiredMixin

from projects.models import Project, ProjectStatus, Deliverable, DeliverableVolume
from qualifications.models import Position


#####################
### Projects View ###
#####################

class ProjectListView(ListView, LoginRequiredMixin):
    model = Project
    context_object_name='projects_list'
    template_name='project_list.html'

    def get_context_data(self, **kwargs):
        context = super(ProjectListView,self).get_context_data(**kwargs)
        context['viewing'] = "all"
        context['projectstatus_list'] = ProjectStatus.objects.all()
        return  context
    
class FilteredProjectListView(ProjectListView):
    
    def get_queryset(self):
        project_status = self.kwargs['filter']
        return self.model.objects.filter(status__name=project_status)

    def get_context_data(self, **kwargs):
        context = super(FilteredProjectListView,self).get_context_data(**kwargs)
        context['viewing'] = self.kwargs['filter']
        return  context

class ProjectDetailView(DetailView,LoginRequiredMixin):
    model = Project()
    template_name='project_detail.html'
    
    
class ProjectCreateView(CreateView,PermissionRequiredMixin):
    model=Project
    template_name='project_form.html'
    permission='projects.add_project'
    fields=['name','number','description','date_start','date_end','customer_name','customer_siglum','wiki_link','project_leader','department','natco','status']
    
    def get_success_url(self):
        return reverse_lazy('project_detail',args=[self.object.id])
    

class ProjectUpdateView(UpdateView,PermissionRequiredMixin):
    model = Project
    template_name='project_form.html' 
    permission = 'projects.change_project'
    fields=['name','number','description','date_start','date_end','customer_name','customer_siglum','wiki_link','project_leader','department','natco','status']
    
    def get_success_url(self):
        return reverse_lazy('project_detail',args=[self.object.id])
    

class ProjectDeleteView(DeleteView,PermissionRequiredMixin):
    model=Project
    permission='projects.delete_project'
    template_name = 'project_confirm_delete.html'
    
    def get_success_url(self):
        return reverse_lazy('projects_list')
    
    

#####################
### Deliverables View ###
#####################

class DeliverableListView(ListView, LoginRequiredMixin):
    model = Deliverable
    context_object_name='deliverables_list'
    template_name='deliverable_list.html'


class DeliverableDetailView(DetailView,LoginRequiredMixin):
    model = Deliverable()
    template_name='deliverable_detail.html'
    
    
class DeliverableCreateView(CreateView,PermissionRequiredMixin):
    model=Deliverable
    template_name='deliverable_form.html'
    permission='projects.add_deliverable'
    fields=['project','service','code','name','description','acceptance_criteria']
    
    def get_success_url(self):
        return reverse_lazy('deliverable_detail',args=[self.object.id])
    

class DeliverableUpdateView(UpdateView,PermissionRequiredMixin):
    model = Deliverable
    template_name='deliverable_form.html' 
    permission = 'projects.change_deliverable'
    fields=['project','service','code','name','description','acceptance_criteria']
    
    def get_success_url(self):
        return reverse_lazy('deliverable_detail',args=[self.object.id])
    

class DeliverableDeleteView(DeleteView,PermissionRequiredMixin):
    model=Deliverable
    template_name='deliverable_confirm_delete.html'
    permission='projects.delete_deliverable'
    
    def get_success_url(self):
        return reverse_lazy('deliverables_list')
    
    
class AddDeliverableVolumeView(CreateView,PermissionRequiredMixin):
    model = DeliverableVolume
    template_name='deliverablevolume_form.html'
    permission='projects.add_deliverablevolume'
    fields=['deliverable','date_start','date_end','quantity','unit_price']
    
    def get_context_data(self, **kwargs):
        context = super(AddDeliverableVolumeView,self).get_context_data(**kwargs)
        deliverable= Deliverable.objects.get(pk=self.kwargs['pk'])
        context['predefined'] = {'deliverable':deliverable}
        return  context
    
    def get_success_url(self):
        return reverse_lazy('deliverablevolume_detail',args=[self.object.id])
    
class DeliverableVolumeUpdateView(UpdateView,PermissionRequiredMixin):
    model = DeliverableVolume
    template_name='deliverablevolume_form.html' 
    permission = 'projects.change_deliverablevolume'
    fields=['deliverable','date_start','date_end','quantity','unit_price']
    
    def get_success_url(self):
        return reverse_lazy('deliverablevolume_detail',args=[self.object.id])


class AddDeliverableFromProjectView(DeliverableCreateView):
    
    def get_context_data(self, **kwargs):
        context = super(AddDeliverableFromProjectView,self).get_context_data(**kwargs)
        project = Project.objects.get(pk=self.kwargs['pk'])
        context['predefined'] = {'project':project}
        return  context
    

projects/templates/criticity_display.html
{% if task.criticity == "H" %}
    "background-color:#F78181;"
{% endif %}

{% if task.criticity == "M" %}
    "background-color:#F4FA58;"
{% endif %}

{% if task.criticity == "L" %}
    "background-color:#A5DF00;"
{% endif %}

projects/templates/deliverable_detail.html
<!-- We need to display this page in a full layout -->
{% extends "base.html" %}

{% block content %}

{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Projects" "projects_list" %}
    {% breadcrumb deliverable.project "project_detail" deliverable.project.id %}
    {% breadcrumb deliverable "deliverable_detail" deliverable.id %}
{% endblock %}


{% render_breadcrumbs %}
<!-- Include the object property -->
{% include "deliverable_property.html" %}

<!-- Include the object property -->
{% include "common/object_actions.html" %}

<hr/>

{% include "deliverablevolume_table.html" with deliverablevolumes_list=deliverable.get_volumes %}
<a href="{% url 'add_deliverablevolume' deliverable.id %}"><i class="fa fa-plus"></i>Add deliverable volume</a>

{% endblock %}

projects/templates/deliverable_form.html
{% extends "base.html" %}

{% block content %}

{% include "fa-decoration.html" with title="Edit Project Deliverable" icon="fa-file-text" block="main" %}

{% include "common/standard_form.html" %}

{% endblock %}

projects/templates/deliverable_list.html
<!-- We need to display this page in a full layout -->
{% extends "base.html" %}

{% block content %}

{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "deliverables" "deliverables_list" %}
{% endblock %}

{% render_breadcrumbs %}

<!-- Include the list of objects -->
{% include "deliverable_table.html" with block="main" datatable_style="dataTableFiltered" %}

{% include "common/list_actions.html" with action_url="create_deliverable" item_name="deliverable" %}

{% endblock %}

projects/templates/deliverable_property.html
{% load currency_filter %}
{% include "fa-decoration.html" with title="Project Deliverable properties" icon="fa-file-text" block="main" %}
<table class="table table-hover">
    <tr><th>project deliverable name</th><td>{{ deliverable.name}}</td></tr>
    <tr><th>project deliverable identifier</th><td>{{ deliverable.code }}</td></tr>
    <tr><th>project name</th><td><a href="{% url 'project_detail' deliverable.project.id %}">{{ deliverable.project}}</a></td></tr>
    <tr><th>service family / service</th><td><a href="{% url 'service' deliverable.service.id %}">{{ deliverable.service}}</a></td></tr>
    <tr><th>description</th><td>{{ deliverable.description|linebreaksbr  }}</td></tr>
    <tr><th>acceptance criteria</th><td>{{ deliverable.acceptance_criteria }}</td></tr>
    <tr><th>total turnover</th><td>{{ deliverable.get_turnover|currency }}</td></tr>
</table>

projects/templates/deliverablevolume_detail.html
<!-- We need to display this page in a full layout -->
{% extends "base.html" %}

{% block content %}

{% load django_bootstrap_breadcrumbs %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Projects" "projects_list" %}
    {% breadcrumb deliverablevolume.deliverable.project "project_detail" deliverablevolume.deliverable.project.id %}
    {% breadcrumb deliverablevolume.deliverable "deliverable_detail" deliverablevolume.deliverable.id %}
    {% breadcrumb deliverablevolume.date_start "deliverablevolume_detail" deliverablevolume.id %}
{% endblock %}

{% render_breadcrumbs %}

<!-- Include the object property -->
{% include "deliverablevolume_property.html" %}

<!-- Include the object property -->
{% include "common/object_actions.html" %}

{% endblock %}

projects/templates/deliverablevolume_list.html
<!-- We need to display this page in a full layout -->
{% extends "base.html" %}

{% block content %}

<!-- Include the list of objects -->
{% include "deliverablevolume_table.html" with block="main" %}

{% comment %} {% include "common/list_actions.html" with action_url="create_deliverablevolume" item_name="deliverable volume" %} {% endcomment %}

{% endblock %}

projects/templates/deliverablevolume_property.html
{% load currency_filter %}
{% include "fa-decoration.html" with title="Project Deliverable Volume properties" icon="fa-line-chart" block="main" %}
<table class="table table-hover">
    <tr><th>project deliverable name</th><td><a href="{% url 'deliverable_detail' deliverablevolume.deliverable.id %}">{{ deliverablevolume.deliverable}}</a></td></tr>
    <tr><th>date start</th><td>{{ deliverablevolume.date_start}}</td></tr>
    <tr><th>date end</th><td>{{ deliverablevolume.date_end}}</td></tr>
    <tr><th>number of units</th><td>{{ deliverablevolume.quantity }}</td></tr>
    <tr><th>unit price</th><td>{{ deliverablevolume.unit_price|currency }} </td></tr>
</table>

projects/templates/deliverablevolume_table.html
{% load currency_filter %}
{% include "fa-decoration.html" with title=title|default:"Project Deliverables Volumes list" icon=icon|default:"fa-line-chart" %}

<table class="table table-condensed table-bordered table-hover dataTable">
    <thead>
    <tr>
        <th>project deliverable name</th>
        <th>date start</th>
        <th>date end</th>
        <th>quantity</th>
        <th>unit price</th>
        <th>total price</th>
    </tr>
    </thead>
    <tbody>
{% for deliverablevolume in deliverablevolumes_list %}
    <tr>
        <td><a href="{% url 'deliverablevolume_detail' deliverablevolume.id %}">{{ deliverablevolume.deliverable }}</a></td>
        <td>{{ deliverablevolume.date_start }}</td>
        <td>{{ deliverablevolume.date_end }}</td>
        <td align="right">{{ deliverablevolume.quantity }}</td>
        <td align="right">{{ deliverablevolume.unit_price|currency }}</td>
        <td align="right">{{ deliverablevolume.get_total_price|currency }}</td>
{% endfor %}
    </tbody>
</table>

projects/templates/project_list.html
<!-- We need to display this page in a full layout -->
{% extends "base.html" %}

{% load django_bootstrap_breadcrumbs %}

{% block content %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Projects" "projects_list" %}
{% endblock %}

{% render_breadcrumbs %}

<ul class="nav nav-pills">
    <li role="presentation" {% if viewing == "all" %}class="active"{% endif %}><a href="{%url "projects_list" %}">All</a></li>
    {% for projectstatus in projectstatus_list %}
    <li role="presentation" {% if viewing|lower == projectstatus|lower %}class="active"{% endif %}><a href="{%url "projects_list_status" projectstatus %}">{{ projectstatus }}</a></li>
    {% endfor %}
</ul>

<!-- Include the list of objects -->
{% include "project_table.html" with block="main" datatable_style="dataTableFiltered" %}

{% include "common/list_actions.html" with action_url="create_project" item_name="project" %}

{% endblock %}

projects/templates/project_property.html
{% load currency_filter %}
{% include "fa-decoration.html" with title=title|default:"Project properties" icon="fa-cubes" block="main" %}
<table class="table table-hover">
    <tr><th>project name</th><td>{{ project.name}}</td></tr>
    <tr><th>project number</th><td>{{ project.number}}</td></tr>
    <tr><th>project leader</th>
        <td>
            {% if project.project_leader %}<a href="{% url 'employee' project.project_leader.id %}">{{project.project_leader}}</a>{% endif %}
        </td>
    </tr>
    <tr><th>project start date</th><td>{{project.date_start}}</td></tr>
    <tr><th>project end date</th><td>{{project.date_end}}</td></tr>
    <tr><th>CIMPA department</th><td>{{project.department}}</td></tr>
    <tr><th>turnover allocation natco</th><td>{{project.get_natco_display}}</td></tr>
    <tr><th>customer name</th><td>{{project.customer_name}}</td></tr>
    <tr><th>customer siglum</th><td>{{project.customer_siglum}}</td></tr>
    <tr><th>description</th><td>{{ project.description|linebreaksbr  }}</td></tr>
    <tr><th>wiki link</th><td><a href="{{project.wiki_link}}">{{ project.wiki_link}}</a></td></tr>
    <tr><th>status</th><td><div class="label {{ project.status.css_class }}">{{ project.status }}</div></td></tr>
    <tr><th>turnover</th><td>{{ project.get_total_turnover|currency }}</td></tr>
</table>

projects/templates/project_table.html
{% load currency_filter %}
{% include "fa-decoration.html" with title=title|default:"Projects list" icon=icon|default:"fa-cubes" %}

{% if projects_list %}
<table class="table table-condensed table-bordered table-hover {{ datatable_style |default:"dataTable" }}">
    <thead>
        <tr>
            <th>number</th>
            <th>name</th>
            <th>department</th>
            <th>project leader</th>
            <th>status</th>
            <th>turnover</th>
        </tr>
    </thead>
    <tbody>
{% for project in projects_list %}
    <tr>
        <td>{{ project.number }}</td>
        <td><a href="{% url 'project_detail' project.id %}">{{ project.name }}</td>
        <td>{{ project.department }}</td>
        <td>
            {% if project.project_leader %}<a href="{% url 'employee' project.project_leader.id %}">{{ project.project_leader }}</a>{% endif %}
        </td>
        <td><div class="label {{ project.status.css_class }}">{{ project.status }}</div></td>
        <td align="right">{{ project.get_total_turnover|currency }}</td>
    </tr>
{% endfor %}
    </tbody>
</table>
{% else %}
<p>No projects found.</p>
{% endif %}

projects/templates/projects_menu.html
<ul class="nav nav-sidebar">
    <li><a href="{% url 'projects_list' %}"><i class="fa fa-fw fa-cubes"></i>&nbsp;Projects</a></li>
    <li><a href="{% url 'deliverables_list' %}"><i class="fa fa-fw fa-file-text"></i>&nbsp;Project Deliverables</a></li>
</ul>

projects/templates/projects_summary.html
{% load staticfiles %}
<h2>Projects Status</h2>
<table>
    <tr>
        <td><a href="{% url 'projects_list' %}"><i class="fa fa-cubes"></i>&nbsp;{{count_projects}} Projects</a> registered</td>
    </tr>
    <tr>
        <td><a href="{% url 'deliverables_list' %}"><i class="fa fa-file-text"></i>&nbsp;{{count_deliverables}} Deliverables</a> registered</td>
    </tr>
</table>